name: Push docker image to the GitHub registry

on:
  push:
    tags:
       - '**'

jobs:
  publish-docker-image:
   runs-on: ubuntu-latest
   steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push the Docker image
        run: |
             docker build .  --tag ghcr.io/imgios/whaley:${{  github.ref_name }} --tag ghcr.io/imgios/whaley:latest
             docker push ghcr.io/imgios/whaley --all-tags
